### ISSUE TITLE
F@H container benchmarks

### ISSUE THREAD

**Issue by abitrolly** [FoldingAtHome/containers#17]
#7 was closed without the resolution about performance, and as I constantly get back to this, I decided to raise the dedicated issue. #8 also contains question about performance on Google Cloud Platform.

The goal is to measure and compare performance of F@H with and without containers on similar hardware. To see if containerization of such payload is efficient, and provides ways to troubleshoot and improve that.

**Comment by PantherX** [comment]
It isn't easy to benchmark since there's no F@H Benchmark that supports the current FahCores. WUs that are assigned are random in nature and even if you do end up getting WUs from the same Project, they can vary in performance.

You can capture WU and test it on different setups but it isn't a very straightforward process: https://foldingforum.org/viewtopic.php?p=335217#p335217

We had done donor who documented the WUs that ran on the same hardware under different setups which might provide you with a bit of insight: https://docs.google.com/spreadsheets/d/1dUXspeOY0pGZQvqaPVUSkjL9O_D4afcE_N8pvDWMXp0/edit#gid=0
