### ISSUE TITLE
Image out of date

### ISSUE THREAD

**Issue by RJSzynal** [FoldingAtHome/containers#4]
Please could you build a new version of the image as a new fah-client version has been released.
Also, it may be worth setting up some sort of auto-triggered pipeline to build a new image whenever a new version of the application is available.

**Comment by RJSzynal** [comment]
If it's any help, you can get the latest version number using the following command so that the dockerfile will always just get whatever is the latest:
`curl -s https://download.foldingathome.org/ | grep "debian-stable-64bit" | grep -Po '(?<=fahclient_)\d.\d.\d'`

**Comment by beberg** [comment]
As mentioned in the README, the containers follow the latest STABLE releases of clients. Right now the benchmark for that is 2 weeks without a fix. So it's intentional the containers aren't following along since the bugs are worse when you have 1000 of them running at a time.

As soon as the 7.6.x client reaches a stable state, the client versions and checksums will be updated.

**Comment by RJSzynal** [comment]
I'm not sure I understand. 7.6 _is_ the latest stable version: https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit/v7.6/fahclient_7.6.9_amd64.deb

**Comment by RJSzynal** [comment]
Also, correct image tagging should give the user the option to run whatever version they want.
I recommend creating 3 tags per build (`Major.Minor.Patch`, `Major.Minor`, and `Major`) to allow people to chose what they follow then update the `latest` tag when you're happy that it is stable. You could also perhaps have some sort of `next` type tag which is the latest build without the 2 week wait.

**Comment by RJSzynal** [comment]
If it helps, here is a Makefile which builds various images: https://github.com/RJSzynal/dockerfiles/blob/master/makefile 
Feel free to copy anything from there.
I would also recommend including whatever you use to actually build the image in this repo (makefile, CI script, whatever) so that people can see how it is built and can make improvement PRs.

For this project I would recommend the following:
```
	version=$$(curl -s https://download.foldingathome.org/ | grep "debian-stable-64bit" | grep -Po '(?<=fahclient_)\d.\d.\d') && \
	docker build -t foldingathome/fah-gpu:$${version} -t foldingathome/fah-gpu:$${version%.*} -t foldingathome/fah-gpu:$${version%%.*} -t foldingathome/fah-gpu:latest . && \
	docker push foldingathome/fah-gpu:$${version} && \
	docker push foldingathome/fah-gpu:$${version%.*} && \
	docker push foldingathome/fah-gpu:$${version%%.*} && \
	docker push foldingathome/fah-gpu:next
```
If it auto-builds nightly then you'll always have the newest versions available without having to do anything.
Then you can manually execute the following when you want to tag latest:
```
docker tag foldingathome/fah-gpu:7.6.9 foldingathome/fah-gpu:latest
docker push foldingathome/fah-gpu:latest
```

Hopefully this is all helpful in reducing the mount of hands-on maintenance this project will require, freeing up you time to work on improvements or other projects.

**Comment by RJSzynal** [comment]
Ah, I've just realised that the `https://download.foldingathome.org/` json returns the previous version and that this must be what you meant by the 2 week delay. 
Apologies for the misunderstanding, I was confused by the fact that the new version is incorrectly under the `https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit` route instead of the `https://download.foldingathome.org/releases/public/release/fahclient/debian-testing-64bit`

In that case, my last example could just tag the build with latest.

**Comment by beberg** [comment]
The team has agreed to a 2-week stabilization period. Now mentioned in the top level README. 7.6.12 is in beta, so that threshold isn't met yet.

We aren't yet committed to following **strict** Semantic Versioning. Once that is the case, there will be the familiar `7`, `7.5`, `7.5.1` style tags, before that it would be misleading. This will probably get sorted out after 7.6 solves the immediate COVID needs.

We have talked about a `nightly` tag, but it comes with some issues. Nightly client builds need to be _watched carefully_ and monitored. Install/uninstall/upgrade test cycles, performance monitoring, etc. Often with short work units, and with tight coordination with the development team. All of those things are much easier with the standard clients than with containers.

**Comment by RJSzynal** [comment]
Thank you for explaining that, I can appreciate it now although I would say that people using a nightly build know exactly what they're getting into and don't expect a stable experience.
